install:
	go install github.com/jackson198608/goProject/pushContentCenter/pushApp 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/pushApp -v

build:
	GOOS=linux GOARCH=amd64 go build github.com/jackson198608/goProject/pushContentCenter/pushApp 


