install:
	go install github.com/jackson198608/goProject/pushContentCenter/channels/location/fansPersons 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/channels/location/fansPersons -v
