install:
	go install github.com/jackson198608/goProject/pushContentCenter/channels/location/breedPersons 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/channels/location/breedPersons -v
