install:
	go install github.com/jackson198608/goProject/realTimeResque

test:
	go test github.com/jackson198608/goProject/realTimeResque -v

build:
	GOOS=linux GOARCH=amd64 go build -o realTimeResque github.com/jackson198608/goProject/realTimeResque