install:
	go install github.com/jackson198608/goProject/weixinPush

test:
	go test github.com/jackson198608/goProject/weixinPush -v

build:
	GOOS=linux GOARCH=amd64 go build github.com/jackson198608/goProject/weixinPush


