install:
	go install github.com/jackson198608/goProject/image/compressImage

test:
	go test github.com/jackson198608/goProject/image/compressImage -v

build:
	GOOS=linux GOARCH=amd64 go build github.com/jackson198608/goProject/image/compressImage


