install:
	go install github.com/jackson198608/goProject/pushContentCenter/channels/location/RecommendAllPersons 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/channels/location/RecommendAllPersons -v
