install:
	go install github.com/jackson198608/goProject/GoHash

test:
	go test github.com/jackson198608/goProject/GoHash -v

build:
	GOOS=linux GOARCH=amd64 go build github.com/jackson198608/goProject/GoHash