install:
	go install github.com/jackson198608/goProject/goumincms/
	cp data/* /etc/
run:

	goumincms thread "/etc/goumincmsnew.json"
	goumincms createnum "/etc/goumincmsnew.json"

	goumincms ask "/etc/goumincmsask.json"
	goumincms createnum "/etc/goumincmsask.json"