install:
	go install github.com/jackson198608/goProject/go_spider/example/gouminwang
run:
	gouminwang "/data/gouminwang/" "http://weixin.sogou.com/weixin?type=2&query=狗与爱的世界&ie=utf8&s_from=input&_sug_=n&_sug_type_=&w=01019900&sut=2593&sst0=1502269098653&lkt=1%2C1502269098550%2C1502269098550" "articleList|0" "/tmp/1.log" 1
