install:
	go install github.com/jackson198608/goProject/pushContentCenter/channels/location/allPersons 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/channels/location/allPersons -v
