install:
	go install github.com/jackson198608/goProject/pushContentCenter/channels/location/clubPersons 

test:
	go test github.com/jackson198608/goProject/pushContentCenter/channels/location/clubPersons -v
