install:
	go install github.com/jackson198608/goProject/gouminMultiMessagePush/channels/bashpush

test:
	go test github.com/jackson198608/goProject/gouminMultiMessagePush/channels/bashpush -v

	go test -test.run TestDo